# -------- Stage 1: Build --------
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache python3 make g++

# Copy package files and tsconfig
COPY package*.json tsconfig.json ./

# Copy scripts and database folder
COPY scripts ./scripts
COPY .db ./.db

# Install dependencies
RUN npm install
RUN npm install --save-dev @types/mongoose

# -------- Stage 2: Runner --------
FROM node:18-alpine AS runner

# Set working directory
WORKDIR /app

# Set environment variables
ENV NODE_ENV=development

# Copy only necessary files from builder
COPY --from=builder /app /app

# Command to run migration
CMD ["npx", "ts-node", "--project", "scripts/tsconfig.json", "scripts/migrate-data.ts"]

